(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),screens=['#titleScreen','#howScreen','#pauseScreen','#resultScreen'];
let W=innerWidth,H=innerHeight,dpr=1,state='title',last=0,acc=0,time=0,spawnT=0,canT=0,score=0,cans=0,distance=0,speed=250,shake=0,dashCd=0,invuln=0,trailHue=185;
let best=Number(localStorage.getItem('spaceCatBest')||0),rocks=[],pickups=[],particles=[],stars=[];
const keys=new Set(),pointer={active:false,x:0,y:0};
const cat={x:0,y:0,vx:0,vy:0,r:22};
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,W<600?1.6:2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);makeStars()}
function makeStars(){stars=Array.from({length:Math.min(140,Math.floor(W*H/7000))},()=>({x:Math.random()*W,y:Math.random()*H,z:.3+Math.random()*1.7,h:Math.random()>.5?190:300}))}
function show(sel){screens.forEach(s=>$(s).classList.toggle('hidden',s!==sel));}
function reset(){rocks=[];pickups=[];particles=[];time=score=cans=distance=spawnT=canT=0;speed=250;dashCd=invuln=0;cat.x=W*.28;cat.y=H*.5;cat.vx=cat.vy=0;$('#best').textContent=best;$('#hud').classList.remove('hidden');$('#dashBtn').classList.remove('hidden','cooldown');show('');state='play';last=performance.now();acc=0}
function start(){reset()}
function pause(){if(state!=='play')return;state='pause';show('#pauseScreen')}
function resume(){if(state!=='pause')return;state='play';show('');last=performance.now()}
function home(){state='title';show('#titleScreen');$('#hud').classList.add('hidden');$('#dashBtn').classList.add('hidden')}
function rand(a,b){return a+Math.random()*(b-a)}
function spawnRock(){const r=rand(16,44),hard=Math.min(1,time/75);rocks.push({x:W+r+20,y:rand(r,H-r),r,vx:-(speed+rand(10,120)+hard*100),vy:rand(-25,25),rot:rand(0,6.28),vr:rand(-2,2),shape:Array.from({length:8},()=>rand(.78,1.12)),h:Math.random()>.8?325:270})}
function spawnCan(){pickups.push({x:W+30,y:rand(45,H-45),r:15,vx:-speed*.72,phase:rand(0,6.28)})}
function burst(x,y,color,n=12){for(let i=0;i<n;i++){let a=rand(0,6.28),v=rand(60,260);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.25,.65),max:.65,color,size:rand(2,6)})}}
function dash(){if(state!=='play'||dashCd>0)return;dashCd=3;invuln=.45;cat.vx+=260;shake=5;burst(cat.x,cat.y,'#ffe35a',22);$('#dashBtn').classList.add('cooldown');toast('霓虹冲刺！')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),800)}
function hit(a,b,rr){let dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<rr*rr}
function end(){state='result';$('#hud').classList.add('hidden');$('#dashBtn').classList.add('hidden');let old=best;score=Math.floor(distance+cans*80);if(score>best){best=score;localStorage.setItem('spaceCatBest',best)}$('#finalScore').textContent=score;$('#finalDistance').textContent=Math.floor(distance)+'m';$('#finalCans').textContent=cans;$('#newBest').textContent=score>old?'✦ 新纪录！ ✦':'';show('#resultScreen')}
function update(dt){time+=dt;speed=250+Math.min(320,time*3.2);distance+=dt*speed/26;dashCd=Math.max(0,dashCd-dt);invuln=Math.max(0,invuln-dt);if(dashCd<=0)$('#dashBtn').classList.remove('cooldown');
 let ax=0,ay=0;if(keys.has('ArrowLeft')||keys.has('KeyA'))ax--;if(keys.has('ArrowRight')||keys.has('KeyD'))ax++;if(keys.has('ArrowUp')||keys.has('KeyW'))ay--;if(keys.has('ArrowDown')||keys.has('KeyS'))ay++;if(pointer.active){let dx=pointer.x-cat.x,dy=pointer.y-cat.y,d=Math.hypot(dx,dy);if(d>8){ax=dx/d;ay=dy/d}}
 cat.vx+=(ax*720-cat.vx*5)*dt;cat.vy+=(ay*720-cat.vy*5)*dt;cat.x+=cat.vx*dt;cat.y+=cat.vy*dt;cat.x=Math.max(cat.r,Math.min(W-cat.r,cat.x));cat.y=Math.max(cat.r,Math.min(H-cat.r,cat.y));cat.vx*=.94;
 spawnT-=dt;canT-=dt;if(spawnT<=0){spawnRock();spawnT=Math.max(.22,rand(.55,1.05)-time*.004)}if(canT<=0){spawnCan();canT=rand(2.1,3.5)}
 for(const r of rocks){r.x+=r.vx*dt;r.y+=r.vy*dt;r.rot+=r.vr*dt;if(invuln<=0&&hit(cat,r,cat.r+r.r*.74)){burst(cat.x,cat.y,'#ff4fd8',34);shake=12;end();return}}
 for(const p of pickups){p.x+=p.vx*dt;p.phase+=dt*4;if(hit(cat,p,cat.r+p.r)){p.dead=true;cans++;score+=80;burst(p.x,p.y,'#ffe35a',16);toast('+1 罐头！')}}
 rocks=rocks.filter(r=>r.x>-r.r*3);pickups=pickups.filter(p=>!p.dead&&p.x>-50);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}particles=particles.filter(p=>p.life>0);shake*=.88;trailHue=(trailHue+dt*7)%360;
 $('#distance').textContent=Math.floor(distance)+'m';$('#cans').textContent=cans}
function drawBg(dt){ctx.fillStyle='#050316';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.5,0,W*.5,H*.5,Math.max(W,H)*.7);g.addColorStop(0,'#171044');g.addColorStop(.55,'#080522');g.addColorStop(1,'#03020e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 ctx.save();ctx.globalCompositeOperation='lighter';for(const s of stars){s.x-=speed*.012*s.z;if(s.x<0){s.x=W;s.y=Math.random()*H}ctx.strokeStyle=`hsla(${s.h},90%,75%,${.22+s.z*.25})`;ctx.lineWidth=s.z;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-(8+speed*.045)*s.z,s.y);ctx.stroke()}for(let i=0;i<4;i++){let y=H*(.18+i*.22)+Math.sin(time*.4+i)*35;ctx.strokeStyle=`hsla(${(trailHue+i*52)%360},100%,60%,${.08+i*.015})`;ctx.lineWidth=2+i;ctx.beginPath();ctx.moveTo(-20,y);ctx.bezierCurveTo(W*.28,y+80,W*.65,y-70,W+20,y+20);ctx.stroke()}ctx.restore()}
function drawRock(r){ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.rot);ctx.shadowColor=`hsl(${r.h} 90% 55%)`;ctx.shadowBlur=12;ctx.fillStyle='#322b55';ctx.strokeStyle=`hsl(${r.h} 85% 65%)`;ctx.lineWidth=3;ctx.beginPath();r.shape.forEach((m,i)=>{let a=i/r.shape.length*6.28,x=Math.cos(a)*r.r*m,y=Math.sin(a)*r.r*m;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#171331';ctx.beginPath();ctx.arc(-r.r*.22,-r.r*.15,r.r*.2,0,6.28);ctx.fill();ctx.restore()}
function drawCan(p){ctx.save();ctx.translate(p.x,p.y+Math.sin(p.phase)*5);ctx.shadowColor='#ffe35a';ctx.shadowBlur=18;ctx.fillStyle='#f7d84a';ctx.fillRect(-13,-15,26,30);ctx.fillStyle='#ff4f70';ctx.fillRect(-13,-5,26,13);ctx.fillStyle='#fff';ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText('鱼',0,6);ctx.strokeStyle='#fff4a8';ctx.strokeRect(-13,-15,26,30);ctx.restore()}
function drawCat(){ctx.save();ctx.translate(cat.x,cat.y);let blink=invuln>0&&Math.floor(time*16)%2===0;if(blink)ctx.globalAlpha=.35;ctx.rotate(cat.vy*.00035);ctx.shadowColor=invuln>0?'#ffe35a':'#44f4ff';ctx.shadowBlur=20;ctx.fillStyle='#7566de';ctx.beginPath();ctx.ellipse(-5,10,30,17,0,0,6.28);ctx.fill();ctx.fillStyle='#ffb347';ctx.beginPath();ctx.moveTo(-27,-8);ctx.lineTo(-20,-30);ctx.lineTo(-7,-13);ctx.lineTo(10,-30);ctx.lineTo(19,-5);ctx.quadraticCurveTo(24,18,-5,22);ctx.quadraticCurveTo(-32,17,-27,-8);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-12,-4,5,0,6.28);ctx.arc(7,-4,5,0,6.28);ctx.fill();ctx.fillStyle='#18132f';ctx.beginPath();ctx.arc(-11,-3,2.4,0,6.28);ctx.arc(8,-3,2.4,0,6.28);ctx.fill();ctx.strokeStyle='#3d2850';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-2,5,5,.2,2.9);ctx.stroke();ctx.fillStyle='#c4faff';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(-4,-5,31,3.45,6.0);ctx.strokeStyle='#44f4ff';ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=.8;ctx.fillStyle='#ff4fd8';ctx.beginPath();ctx.moveTo(-33,5);ctx.lineTo(-55,15+rand(-3,3));ctx.lineTo(-34,22);ctx.fill();ctx.restore()}
function render(){ctx.save();if(shake){ctx.translate(rand(-shake,shake),rand(-shake,shake))}drawBg();for(const p of pickups)drawCan(p);for(const r of rocks)drawRock(r);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;if(state==='play'||state==='pause')drawCat();ctx.restore()}
function loop(now){let dt=Math.min(.05,(now-last)/1000||0);last=now;if(state==='play'){acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}}render();requestAnimationFrame(loop)}
addEventListener('resize',resize);addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();dash()}if(e.code==='Escape')state==='play'?pause():resume()});addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(state==='play'){pointer.active=true;pointer.x=e.clientX;pointer.y=e.clientY;canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(pointer.active){pointer.x=e.clientX;pointer.y=e.clientY}});canvas.addEventListener('pointerup',()=>pointer.active=false);canvas.addEventListener('pointercancel',()=>pointer.active=false);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});
$('#startBtn').onclick=()=>show('#howScreen');$('#howBtn').onclick=()=>show('#howScreen');$('#playBtn').onclick=start;$('#pauseBtn').onclick=pause;$('#resumeBtn').onclick=resume;$('#quitBtn').onclick=home;$('#restartBtn').onclick=start;$('#homeBtn').onclick=home;$('#dashBtn').onclick=e=>{e.stopPropagation();dash()};resize();$('#best').textContent=best;requestAnimationFrame(loop);
})();
