(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),catSprite=new Image();catSprite.src='pixel-cat.png';
const $=s=>document.querySelector(s),screens=['#titleScreen','#howScreen','#pauseScreen','#resultScreen'];
let W=innerWidth,H=innerHeight,dpr=1,state='title',last=0,acc=0,time=0,spawnT=0,canT=0,score=0,cans=0,combo=0,comboTime=0,lives=3,distance=0,speed=250,shake=0,cameraY=0,dashCharges=0,dashFish=0,dashTime=0,dashX=1,dashY=0,devourCd=0,devourTime=0,invuln=0,trailHue=185;
let best=Number(localStorage.getItem('spaceCatBest')||0),rocks=[],pickups=[],particles=[],stars=[],bossBullets=[];
const music={audio:$('#bgm'),muted:localStorage.getItem('spaceCatMuted')==='1',start(){this.audio.volume=.28;this.audio.muted=this.muted;this.audio.play().catch(()=>{});$('#musicBtn').textContent=this.muted?'♩':'♫'},toggle(){this.muted=!this.muted;this.audio.muted=this.muted;if(!this.muted)this.audio.play().catch(()=>{});localStorage.setItem('spaceCatMuted',this.muted?'1':'0');$('#musicBtn').textContent=this.muted?'♩':'♫'}};
const keys=new Set(),pointer={active:false,x:0,y:0},joy={active:false,x:0,y:0,id:null};
const cat={x:0,y:0,vx:0,vy:0,r:22,face:1,angle:0};
const boss={active:false,cycle:0,time:0,x:0,y:0,shot:0,next:120,warned:false,warnTick:5};
function resize(){const vv=window.visualViewport;W=Math.round(vv?vv.width:innerWidth);H=Math.round(vv?vv.height:innerHeight);document.documentElement.style.setProperty('--app-height',H+'px');dpr=Math.min(devicePixelRatio||1,W<600?1.6:2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);makeStars()}
function makeStars(){stars=Array.from({length:Math.min(140,Math.floor(W*H/7000))},()=>({x:Math.random()*W,y:Math.random()*H,z:.3+Math.random()*1.7,h:Math.random()>.5?190:300}))}
function show(sel){screens.forEach(s=>$(s).classList.toggle('hidden',s!==sel));}
function reset(){rocks=[];pickups=[];particles=[];bossBullets=[];time=score=cans=combo=comboTime=distance=spawnT=canT=0;lives=3;speed=250;cameraY=0;dashCharges=dashFish=dashTime=devourCd=devourTime=invuln=0;boss.active=false;boss.cycle=0;boss.time=0;boss.next=120;boss.warned=false;boss.warnTick=5;cat.x=W*.28;cat.y=H*.5;cat.vx=cat.vy=0;cat.face=1;cat.angle=0;$('#best').textContent=best;$('#lives').textContent='♥♥♥';$('#hud').classList.remove('hidden');$('#dashBtn').classList.remove('hidden','cooldown');$('#dashBtn').classList.add('cooldown');$('#devourBtn').classList.remove('hidden','cooldown','active');if(matchMedia('(pointer:coarse)').matches)$('#joystick').classList.remove('hidden');show('');state='play';last=performance.now();acc=0}
async function enterLandscape(){if(!matchMedia('(pointer:coarse)').matches)return;try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch(e){}try{if(screen.orientation&&screen.orientation.lock)await screen.orientation.lock('landscape')}catch(e){}}
function start(){enterLandscape();music.start();reset()}
function pause(){if(state!=='play')return;state='pause';music.audio.pause();show('#pauseScreen')}
function resume(){if(state!=='pause')return;state='play';if(!music.muted)music.audio.play().catch(()=>{});show('');last=performance.now()}
function home(){state='title';music.audio.pause();music.audio.currentTime=0;show('#titleScreen');$('#hud').classList.add('hidden');$('#dashBtn').classList.add('hidden');$('#devourBtn').classList.add('hidden');$('#joystick').classList.add('hidden')}
function rand(a,b){return a+Math.random()*(b-a)}
function spawnRock(){let type='normal',roll=Math.random();if(time>25&&roll<.23)type='dart';else if(time>50&&roll<.43)type='zigzag';else if(time>75&&roll<.58)type='giant';const r=type==='dart'?rand(12,19):type==='giant'?rand(43,58):rand(18,38),hard=Math.min(1,time/90),y=rand(r,H-r);rocks.push({type,x:W+r+20,y,baseY:y,r,vx:-(speed+(type==='dart'?260:type==='giant'?-70:rand(20,120))+hard*80),vy:rand(-18,18),phase:rand(0,6.28),rot:rand(0,6.28),vr:rand(-2,2),shape:Array.from({length:type==='dart'?5:8},()=>rand(.78,1.12)),h:type==='dart'?35:type==='zigzag'?190:type==='giant'?320:270})}
function spawnCan(){pickups.push({x:W+30,y:rand(45,H-45),r:15,vx:-speed*.72,phase:rand(0,6.28)})}
function dropFish(x,y){pickups.push({x,y,r:14,vx:-55,phase:rand(0,6.28)})}
function burst(x,y,color,n=12){for(let i=0;i<n;i++){let a=rand(0,6.28),v=rand(60,260);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.25,.65),max:.65,color,size:rand(2,6)})}}
function dash(){if(state!=='play')return;if(dashCharges<=0){toast(`还差 ${5-dashFish} 条小鱼干`);return}if(devourTime>0){toast('吞噬中不能冲刺');return}dashCharges--;dashTime=3.2;invuln=3.25;dashX=1;dashY=0;if(pointer.active){dashX=pointer.x-cat.x;dashY=pointer.y-cat.y;let d=Math.hypot(dashX,dashY)||1;dashX/=d;dashY/=d}else{dashX=(keys.has('ArrowLeft')||keys.has('KeyA'))?-1:1;dashY=(keys.has('ArrowUp')||keys.has('KeyW'))?-0.65:(keys.has('ArrowDown')||keys.has('KeyS'))?.65:0}cat.vx=dashX*560;cat.vy=dashY*560;shake=10;burst(cat.x,cat.y,'#44f4ff',38);if(dashCharges<=0)$('#dashBtn').classList.add('cooldown');toast(`冲击护盾 · 剩余 ${dashCharges} 次`)}
function devour(){if(state!=='play'||devourCd>0)return;if(dashTime>0){toast('冲刺中不能吞噬');return}devourCd=30;devourTime=5;invuln=Math.max(invuln,.35);$('#devourBtn').classList.add('cooldown','active');burst(cat.x,cat.y,'#ff4fd8',55);toast('宇宙吞噬 · 5秒！')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),800)}
function hit(a,b,rr){let dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<rr*rr}
function damage(){if(invuln>0)return false;lives--;invuln=1.5;shake=10;burst(cat.x,cat.y,'#ff4fd8',30);$('#lives').textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);toast(lives>0?`受伤！还剩 ${lives} 条命`:'猫猫撞晕啦！');if(lives<=0)end();return true}
function end(){state='result';$('#hud').classList.add('hidden');$('#dashBtn').classList.add('hidden');$('#devourBtn').classList.add('hidden');$('#joystick').classList.add('hidden');let old=best;score=Math.floor(distance)+score;if(score>best){best=score;localStorage.setItem('spaceCatBest',best)}$('#finalScore').textContent=score;$('#finalDistance').textContent=Math.floor(distance)+'m';$('#finalCans').textContent=cans;$('#newBest').textContent=score>old?'✦ 新纪录！ ✦':'';show('#resultScreen')}
function update(dt){
 time+=dt;speed=250+Math.min(320,time*3.2);distance+=dt*speed/26;dashTime=Math.max(0,dashTime-dt);devourCd=Math.max(0,devourCd-dt);devourTime=Math.max(0,devourTime-dt);invuln=Math.max(0,invuln-dt);comboTime=Math.max(0,comboTime-dt);if(comboTime<=0)combo=0;
 if(dashCharges>0)$('#dashBtn').classList.remove('cooldown');else $('#dashBtn').classList.add('cooldown');if(devourCd<=0)$('#devourBtn').classList.remove('cooldown');if(devourTime<=0)$('#devourBtn').classList.remove('active');
 let ax=0,ay=0;if(keys.has('ArrowLeft')||keys.has('KeyA'))ax--;if(keys.has('ArrowRight')||keys.has('KeyD'))ax++;if(keys.has('ArrowUp')||keys.has('KeyW'))ay--;if(keys.has('ArrowDown')||keys.has('KeyS'))ay++;if(joy.active){ax=joy.x;ay=joy.y}else if(pointer.active){let dx=pointer.x-cat.x,dy=pointer.y-cat.y,d=Math.hypot(dx,dy);if(d>8){ax=dx/d;ay=dy/d}}
 if(dashTime<=0){cat.vx+=(ax*430-cat.vx)*dt*8;cat.vy+=(ay*430-cat.vy)*dt*8}else{if(ax||ay){let d=Math.hypot(ax,ay)||1;dashX+=(ax/d-dashX)*dt*5;dashY+=(ay/d-dashY)*dt*5;let n=Math.hypot(dashX,dashY)||1;dashX/=n;dashY/=n}cat.vx+=(dashX*600-cat.vx)*dt*6;cat.vy+=(dashY*600-cat.vy)*dt*6}cat.x+=cat.vx*dt;cat.y+=cat.vy*dt;cat.x=Math.max(cat.r,Math.min(W-cat.r,cat.x));cat.y=Math.max(cat.r,Math.min(H-cat.r,cat.y));cameraY+=(-ay*22-cameraY)*dt*6;
 if(!boss.active&&!boss.warned&&time>=boss.next-5){boss.warned=true;boss.warnTick=5;toast('⚠ BOSS 5 秒后抵达！');shake=5}if(boss.warned&&!boss.active&&time<boss.next){let left=Math.ceil(boss.next-time);if(left<boss.warnTick){boss.warnTick=left;toast(`BOSS 倒计时 ${left}`)}}if(!boss.active&&time>=boss.next){boss.cycle++;boss.next+=120;boss.warned=false;boss.active=true;boss.time=24;boss.x=W+90;boss.y=H*.5;boss.shot=.7;bossBullets=[];for(let i=0;i<Math.min(3,rocks.length);i++)dropFish(rocks[i].x,rocks[i].y);for(const r of rocks)burst(r.x,r.y,'#44f4ff',5);rocks=[];toast('⚠ BOSS 弹幕来袭！');shake=14}
 if(boss.active){boss.time-=dt;boss.x+=(W-105-boss.x)*dt*2.4;boss.y=H*.5+Math.sin(time*1.3)*H*.28;boss.shot-=dt;if(boss.shot<=0){const count=10+Math.min(8,boss.cycle*2),base=time*.7;for(let i=0;i<count;i++){let a=base+i/count*6.283,v=145+boss.cycle*12;bossBullets.push({x:boss.x-28,y:boss.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:7})}let aim=Math.atan2(cat.y-boss.y,cat.x-boss.x),fan=boss.cycle>=2?[-.22,0,.22]:[0];for(const spread of fan)bossBullets.push({x:boss.x-30,y:boss.y,vx:Math.cos(aim+spread)*255,vy:Math.sin(aim+spread)*255,r:10});boss.shot=Math.max(.28,.58-boss.cycle*.035)}if(boss.time<=0){boss.active=false;bossBullets=[];toast('弹幕突破！+500');score+=500}}
 spawnT-=dt;canT-=dt;if(!boss.active&&spawnT<=0){spawnRock();spawnT=Math.max(.22,rand(.55,1.05)-time*.004)}if(canT<=0){spawnCan();canT=rand(2.1,3.5)}
 for(const r of rocks){if(r.type==='zigzag'&&devourTime<=0)r.vy=Math.sin(time*4+r.phase)*170;if(devourTime>0){let dx=cat.x-r.x,dy=cat.y-r.y,d=Math.hypot(dx,dy)||1;r.vx=dx/d*900;r.vy=dy/d*900}r.x+=r.vx*dt;r.y+=r.vy*dt;r.rot+=r.vr*dt;if(hit(cat,r,cat.r+r.r*.74)){if(dashTime>0){r.dead=true;dropFish(r.x,r.y);burst(r.x,r.y,'#44f4ff',28);shake=7}else if(devourTime>0){r.dead=true;score+=50;burst(r.x,r.y,'#ff4fd8',18)}else if(invuln<=0){r.dead=true;if(damage()&&state==='result')return}}}
 for(const p of pickups){if(devourTime>0){let dx=cat.x-p.x,dy=cat.y-p.y,d=Math.hypot(dx,dy)||1;p.vx=dx/d*1100;p.vy=dy/d*1100}else p.vy=0;p.x+=p.vx*dt;p.y+=p.vy*dt;p.phase+=dt*4;if(hit(cat,p,cat.r+p.r)){p.dead=true;cans++;combo++;comboTime=3;let reward=80+Math.min(320,(combo-1)*20);score+=reward;if(dashCharges<3){dashFish++;if(dashFish>=5){dashFish=0;dashCharges++;toast(`获得护盾冲刺！${dashCharges}/3`)}}burst(p.x,p.y,'#ffe35a',16);if(dashFish||dashCharges>=3)toast(combo>1?`小鱼干 ×${combo} · 蓄力 ${dashFish}/5`:`冲刺蓄力 ${dashFish}/5`)}}
 for(const b of bossBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(hit(cat,b,cat.r+b.r)){b.dead=true;if(invuln>0)burst(b.x,b.y,'#44f4ff',8);else if(damage()&&state==='result')return}}
 rocks=rocks.filter(r=>!r.dead&&r.x>-r.r*3);pickups=pickups.filter(p=>!p.dead&&p.x>-50);bossBullets=bossBullets.filter(b=>!b.dead&&b.x>-40&&b.x<W+40&&b.y>-40&&b.y<H+40);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}particles=particles.filter(p=>p.life>0);shake*=.88;trailHue=(trailHue+dt*7)%360;
 $('#distance').textContent=Math.floor(distance)+'m';$('#cans').textContent=combo>1?`${cans} ×${combo}`:cans;$('#best').textContent=Math.max(best,Math.floor(distance)+score);$('#dashBtn small').textContent=dashTime>0?dashTime.toFixed(1)+'s':`冲刺 ${dashCharges}/3`;$('#devourBtn small').textContent=devourTime>0?devourTime.toFixed(1)+'s':devourCd>0?Math.ceil(devourCd)+'s':'吞噬'
}
function drawBg(dt){ctx.fillStyle='#050316';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.5,0,W*.5,H*.5,Math.max(W,H)*.7);g.addColorStop(0,'#171044');g.addColorStop(.55,'#080522');g.addColorStop(1,'#03020e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 ctx.save();ctx.globalCompositeOperation='lighter';for(const s of stars){s.x-=speed*.012*s.z;if(s.x<0){s.x=W;s.y=Math.random()*H}ctx.strokeStyle=`hsla(${s.h},90%,75%,${.22+s.z*.25})`;ctx.lineWidth=s.z;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-(8+speed*.045)*s.z,s.y);ctx.stroke()}for(let i=0;i<4;i++){let y=H*(.18+i*.22)+Math.sin(time*.4+i)*35;ctx.strokeStyle=`hsla(${(trailHue+i*52)%360},100%,60%,${.08+i*.015})`;ctx.lineWidth=2+i;ctx.beginPath();ctx.moveTo(-20,y);ctx.bezierCurveTo(W*.28,y+80,W*.65,y-70,W+20,y+20);ctx.stroke()}ctx.restore()}
function drawRock(r){ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.rot);ctx.shadowColor=`hsl(${r.h} 90% 55%)`;ctx.shadowBlur=12;ctx.fillStyle='#322b55';ctx.strokeStyle=`hsl(${r.h} 85% 65%)`;ctx.lineWidth=3;ctx.beginPath();r.shape.forEach((m,i)=>{let a=i/r.shape.length*6.28,x=Math.cos(a)*r.r*m,y=Math.sin(a)*r.r*m;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#171331';ctx.beginPath();ctx.arc(-r.r*.22,-r.r*.15,r.r*.2,0,6.28);ctx.fill();ctx.restore()}
function drawCan(p){ctx.save();ctx.translate(p.x,p.y+Math.sin(p.phase)*5);ctx.shadowColor='#ffe35a';ctx.shadowBlur=16;ctx.fillStyle='#fff1a3';ctx.fillRect(-10,-5,20,10);ctx.fillRect(-3,-9,11,18);ctx.fillStyle='#ff9d2e';ctx.fillRect(7,-3,7,6);ctx.fillStyle='#18132f';ctx.fillRect(-7,-2,3,3);ctx.fillStyle='#ffe35a';ctx.fillRect(-15,-7,6,14);ctx.fillRect(-12,-3,5,6);ctx.restore()}
function drawBoss(){if(!boss.active)return;ctx.save();ctx.translate(boss.x,boss.y);ctx.shadowColor='#ff4fd8';ctx.shadowBlur=28;ctx.fillStyle='#38165f';ctx.strokeStyle='#ff4fd8';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,58,0,6.283);ctx.fill();ctx.stroke();ctx.fillStyle='#a95cff';ctx.fillRect(-38,-30,76,60);ctx.fillStyle='#0a051f';ctx.fillRect(-24,-13,14,17);ctx.fillRect(12,-13,14,17);ctx.fillStyle='#fff';ctx.fillRect(-20,-10,6,7);ctx.fillRect(16,-10,6,7);ctx.fillStyle='#ff4fd8';ctx.fillRect(-17,17,34,8);ctx.restore()}
function drawPowers(){if(dashTime>0){let pulse=(Math.sin(time*13)+1)*.5;ctx.save();ctx.translate(cat.x,cat.y);ctx.strokeStyle=`rgba(68,244,255,${.7+pulse*.25})`;ctx.lineWidth=5;ctx.shadowColor='#44f4ff';ctx.shadowBlur=24;ctx.beginPath();ctx.arc(0,0,44+pulse*9,0,6.283);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,34,0,6.283);ctx.stroke();ctx.restore()}if(devourTime>0){ctx.save();ctx.translate(cat.x,cat.y);ctx.strokeStyle='#ff4fd8';ctx.lineWidth=4;ctx.shadowColor='#ff4fd8';ctx.shadowBlur=25;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(0,0,55+i*23+(time*65)%23,0,6.283);ctx.stroke()}ctx.fillStyle='#090313';ctx.beginPath();ctx.ellipse(49,5,16,25,0,0,6.283);ctx.fill();ctx.restore()}}
function drawCat(){ctx.save();ctx.translate(Math.round(cat.x),Math.round(cat.y+Math.sin(time*10)*2));if(Math.abs(cat.vx)>18)cat.face=cat.vx<0?-1:1;let target=Math.atan2(cat.vy,Math.max(55,Math.abs(cat.vx)))*.7*cat.face;cat.angle+=(target-cat.angle)*.18;ctx.rotate(cat.angle);ctx.scale(cat.face,1);if(invuln>0&&Math.floor(time*16)%2===0)ctx.globalAlpha=.35;ctx.imageSmoothingEnabled=false;ctx.shadowColor=invuln>0?'#ffe35a':'#44f4ff';ctx.shadowBlur=12;if(catSprite.complete)ctx.drawImage(catSprite,300,300,930,380,-68,-29,124,51);ctx.restore()}
function render(){ctx.save();ctx.translate(0,cameraY);if(shake){ctx.translate(rand(-shake,shake),rand(-shake,shake))}drawBg();for(const p of pickups)drawCan(p);for(const r of rocks)drawRock(r);for(const b of bossBullets){ctx.shadowColor='#ff4fd8';ctx.shadowBlur=12;ctx.fillStyle='#ff7be5';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,6.283);ctx.fill()}drawBoss();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;if(state==='play'||state==='pause'){drawCat();drawPowers()}ctx.restore()}
function loop(now){let dt=Math.min(.05,(now-last)/1000||0);last=now;if(state==='play'){acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}}render();requestAnimationFrame(loop)}
addEventListener('resize',resize);if(window.visualViewport){visualViewport.addEventListener('resize',resize);visualViewport.addEventListener('scroll',resize)}addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();dash()}if(e.code==='KeyE'){e.preventDefault();devour()}if(e.code==='Escape')state==='play'?pause():resume()});addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(state==='play'){pointer.active=true;pointer.x=e.clientX;pointer.y=e.clientY;canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(pointer.active){pointer.x=e.clientX;pointer.y=e.clientY}});canvas.addEventListener('pointerup',()=>pointer.active=false);canvas.addEventListener('pointercancel',()=>pointer.active=false);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});
function moveJoy(e){const r=$('#joystick').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,limit=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy)||1;if(d>limit){dx=dx/d*limit;dy=dy/d*limit}joy.x=dx/limit;joy.y=dy/limit;$('#joystickKnob').style.transform=`translate(${dx}px,${dy}px)`}
$('#joystick').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();joy.active=true;joy.id=e.pointerId;try{$('#joystick').setPointerCapture(e.pointerId)}catch(err){}moveJoy(e)});$('#joystick').addEventListener('pointermove',e=>{if(joy.active&&e.pointerId===joy.id){e.preventDefault();moveJoy(e)}});function releaseJoy(e){if(e&&joy.id!==null&&e.pointerId!==joy.id)return;joy.active=false;joy.id=null;joy.x=joy.y=0;$('#joystickKnob').style.transform='translate(0,0)'}$('#joystick').addEventListener('pointerup',releaseJoy);$('#joystick').addEventListener('pointercancel',releaseJoy);addEventListener('blur',()=>{pointer.active=false;releaseJoy()});
$('#startBtn').onclick=()=>show('#howScreen');$('#howBtn').onclick=()=>show('#howScreen');$('#playBtn').onclick=start;$('#musicBtn').onclick=()=>music.toggle();$('#pauseBtn').onclick=pause;$('#resumeBtn').onclick=resume;$('#quitBtn').onclick=home;$('#restartBtn').onclick=start;$('#homeBtn').onclick=home;$('#dashBtn').onclick=e=>{e.stopPropagation();dash()};$('#devourBtn').onclick=e=>{e.stopPropagation();devour()};resize();$('#best').textContent=best;requestAnimationFrame(loop);
})();
